version: 0.0
os: linux
files:
  - source: /your_rust_binary
    destination: /home/ec2-user/myapp
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
