version: 0.2

phases:
  build:
    commands:
      # Build the Rust backend using Docker
      - echo "Building the Rust backend with Docker..."
      - docker build -t simple-docker-service-06cf555716e1 -f ./Backend/Dockerfile ./Backend
      - docker tag simple-docker-service-06cf555716e1:latest 831511836258.dkr.ecr.us-west-1.amazonaws.com/simple-docker-service-06cf555716e1:latest

  post_build:
    commands:
      # Push the Docker image to Amazon ECR
      - echo "Pushing the Docker image to Amazon ECR..."
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 831511836258.dkr.ecr.us-west-1.amazonaws.com
      - docker push 831511836258.dkr.ecr.us-west-1.amazonaws.com/simple-docker-service-06cf555716e1:latest
      - echo "Docker image pushed successfully."

artifacts:
  files:
    - Backend/Dockerfile
    - Backend/Cargo.toml
    - Backend/Cargo.lock
    - Backend/src/**/*
    - Backend/static/**/*
